name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Action
      # You may pin to the exact commit or the version.
      # uses: isbang/compose-action@fab6f72bef82b75de541a7b9da1d23412953c2bd
      uses: isbang/compose-action@v1.0.0
      #with:
        # relative path to compose file
        #compose-file: # optional, default is ./docker-compose.yml
        # additional options to pass to `docker-compose down` command
        #down-flags: # optional, default is 
